### ISSUE TITLE
Which License?

### ISSUE THREAD

**Issue by donald-w** [kamranzafar/JCL#44]
I was looking at using this library and wanted to understand the licensing.  The code itself appears to be marked with Apache 2.0, but the 
JCL/JCL2/core/src/main/resources/LICENSE.txt and 
JCL2/pom.xml
both indicate GNU LGPL

Could you let me know which it is? I'm happy to put together a PR for full conversion to Apache 2.0, which I'd need to incorporate this into my project.

Thanks
Donald

**Comment by kamranzafar** [comment]
The license is Apache 2.0. Initially it used to be LGPL but it has changed to ASL.

**Comment by donald-w** [comment]
Ok great, shall I send you a PR to make it all consistent? Happy new year
when it comes.

**Comment by kamranzafar** [comment]
Thanks, yes please send a PR, will pull merge. And Happy New Year to you.

**Comment by kamranzafar** [comment]
thanks for the PR, the changes will go in the next release.
