### ISSUE TITLE
2.8 Release

### ISSUE THREAD

**Issue by mumrah** [kamranzafar/JCL#49]
Are there plans on a 2.8 release? Is this project still active?

**Comment by kamranzafar** [comment]
Hi there, the project is still active.. i need to plan a release, there will be a couple of fixes and improvements checked in soon. Hopefully 2.8 will be available later this month. All relevant contributions are welcome.

**Comment by mumrah** [comment]
Awesome, thanks!

**Comment by mumrah** [comment]
(friendly bump 😃 )

**Comment by kamranzafar** [comment]
thanks for reminding me.. working on it :)

**Comment by kamranzafar** [comment]
Version 2.8 is released.
