### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GillesBodart** [kamranzafar/JCL#52]
Is there a possibility to retrieve the Class object without instantiate the Object : 

Here's an example
`
JarClassLoader jcl = new JarClassLoader();
JclObjectFactory factory = JclObjectFactory.getInstance();
Class<?> clazz = factory.classOf(jcl,"com.myclass");

`
Thanks in advance

**Comment by kamranzafar** [comment]
You could use the loadClass method of jcl like:

Class<?> clazz = jcl.loadClass("com.MyClass");

**Comment by GillesBodart** [comment]
Perfect !! it's what I wanted !!
