### ISSUE TITLE
Which license is JCL licensed under - Apache 2 or GPL 3?

### ISSUE THREAD

**Issue by brett-berger** [kamranzafar/JCL#58]
In the [Overview](https://github.com/kamranzafar/JCL/blob/jcl-2.8/README.textile), it states that JCL 2.8 is licensed under an Apache 2 License, however if you look at the license found https://github.com/kamranzafar/JCL/blob/jcl-2.8/JCL/LICENSE  it's a GPL 3 license.  Which is correct?

**Comment by kamranzafar** [comment]
JCL is licensed under Apache license 2. All references to old GPL3 will be removed in the next release.

**Comment by brett-berger** [comment]
Perfect. Thanks!
